# Generated by Django 5.2.5 on 2025-09-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author_tag_alter_post_date_post_author_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_path',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
    ]
